### ISSUE TITLE
Freezing with message "Starting ergoemacs command loop"

### ISSUE THREAD

**Issue by dunmaksim** [ergoemacs/ergoemacs-mode#353]
Hello!

I use ergoemacs from MELPA. I see the message "Starting ergoemacs command loop" after one of latest update after EMACS start (but not always, 8/10). EMACS freezes and work only Alt+F4. Ctrl+G, Ctrl+Break and other keybindings not works. After removing ergoemacs-mode package all works, but I can't not use him.

**Comment by mlf176f2** [comment]
The version on melpa is unstable.  You can use the stable version (stable.melpa), where all the bugs passed the test.  Otherwise, as a work-around you could also use:

```lisp
(setq ergoemacs-command-loop-type nil)
```
With this option the following things are unsupported:
- Arrow keys and other keys no longer work in terminals under certain key layouts (anyone that uses Alt+O)
- Command mode ergoemacs no longer works.
-  Extended shift-selection no longer works (that is M-> is translated to M-. if it is unbound and assumed that shit-selection is enabled; this doesn't work in normal emacs).
- The apps key making keys "sticky" sort of like `god-mode` does not work.
- Delete and edit key sequences also do not work.
- The command loop shows emacs keyboard conventions (instead of ergoemacs-mode ones)

My suggestion is to use the stable version of ergoemacs-mode.

**Comment by mlf176f2** [comment]
I have reproduced the bug, but haven't figured out where the issue in the hanging of emacs occurs.  What version of emacs are you using.

**Comment by mrkkrp** [comment]
@mlf176f2, Hi, this has been originally posted at Emacs Stackexchange: http://emacs.stackexchange.com/questions/14807/start-ergoemacs-command-loop-how-to-fix-break-my-work

This post says that Emacs is built from source and its version is 24.5.1.

(I just wanted to provide link to Emacs Stackexchange question).

**Comment by dunmaksim** [comment]
Thanks! I switch to melpa-stable now.

**Comment by mlf176f2** [comment]
Thanks @mrkkp
