### ISSUE TITLE
backward-word binding in dired with dired+ on

### ISSUE THREAD

**Issue by kornevik** [ergoemacs/ergoemacs-mode#423]
Dear ergoemacs developer,

Not sure if it is a bug or some problem with my settings but in dired (with dired+ on) when I press `M-u` (i.e. `backward-word` in default ergoemacs qwerty theme) it asks me if I want to bookmark the file instead (i.e. `diredp-do-bookmark` which is strange because in dired+.el I found only `(define-key dired-mode-map "\M-b"    'diredp-do-bookmark)` ). 

When I tried the following after loading `dired-plus` niether was working and `M-u` still was calling `diredp-do-bookmark`:
```elisp
(define-key dired-mode-map "\M-u" nil)
(define-key dired-mode-map "\M-u" 'backward-word)
```
However, this one solved the problem (but it was not obvious to me)
```elisp
(define-key dired-mode-map "\M-b" nil)
```
Anyway, maybe it could be fixed in ergoemacs-mode so it would not rebind `dried+` keys to its defaults keys (i.e. `M-b` to `M-u`).

Kind regards,
Stas

**Comment by mattfidler** [comment]
Thanks,

This is due to dired+ and ergoemacs-mode interaction.  Since dired uses
emacs' default backward word keyboard shortcut of M-b, ergoemacs-mode
thinks that is what is intended for backward-word.   I agree with your
assessment in this case.  most cases modes overwrite default emacs keys to
provide better or different functionality for the standard keys.

On Wed, Jul 20, 2016, 11:50 AM Stanislav Vlasov <notifications@github.com>
wrote:

> Dear ergoemacs developer,
>
> Not sure if it is a bug or some poblem with my settings but in dired (with
> dired+ on) when I press M-u (i.e. backward-word in default ergoemacs
> qwerty theme) it asks me if I want to bookmark the file instead (i.e.
> diredp-do-bookmark which is strange because in dired+.el I found only (define-key
> dired-mode-map "\M-b" 'diredp-do-bookmark) ).
>
When I tried the following after loading dired-plus niether was working and

**Comment by mattfidler** [comment]
I fixed the `backward-word` keyboard shortcut, and added a <kbd>Ctrl</kbd>+<kbd>b</kbd> keybinding to the `diredp-do-bookmark-command`.

Also there seems to be some times, depending on your configuration setup, when changing major mode or minor mode bindings doesn't work correctly. 

This can be fixed by wrapping your keys in a component and requiring it

```lisp
(ergoemacs-component dired-fixes ()
  "Fixes dired components."
  (define-key dired-mode-map (kbd "M-u") 'backward-word)
  (define-key dired-mode-map (kbd "C-b") 'diredp-do-bookmark))

(ergoemacs-require 'dired-fixes)
```
