### ISSUE TITLE
Ergoemacs loading ~5 seconds.

### ISSUE THREAD

**Issue by Foxly1990** [ergoemacs/ergoemacs-mode#426]
Hi! Why ergoemacs have a load 5 seconds? But if i'm try use evil-mode load instant.

**Comment by mattfidler** [comment]
Good question.  

`evil-mode` sets up a keymap immediately;  it does not look up keybindings based on all the keymaps installed in emacs. 

In the first start-up, ergoemacs-mode does the following:
- Runs emacs without any extensions
- Examines all the default keys of emacs
- Saves the keymaps based on the emacs version and platform (some platforms have slightly different keys). 

This should only occur once per emacs platform/version run.

The next thing that `ergoemacs-mode` does is:
- Setup the translation between keyboard layouts that you are using (say Russian and QWERTY)
- Setup  the theme to work in the current environment

The last think is trying to lookup keys to ensure maximum compatability.  This is done by:
- examining every active keymap, 
- translating standard emacs keys to their equivalent in ergoemacs-mode.
This will usually allow the right actions, and maximum compatibility with emacs packages.  For example, the save key will behave correctly in `org-agenda-mode` even though the commands are different.  This is because both org-agenda-mode and default emacs define the key <kbd>Ctrl</kbd>+<kbd>X</kbd> <kbd>Ctrl</kbd>+<kbd>S</kbd> for the emacs save.

 Sometimes, depending on your setup, some of these things are cached, and will take less time on startup.  Unfortunately, I haven't figured out how to cache these so that the keys run almost instantaneously. You can submit a pull request if you have something that works instantly.

If you ever want to check what is slowing `ergoemacs-mode`'s slow-down, you can always issue the command <kbd>Alt</kbd>+<kbd>a</kbd> `ergoemacs-timing-results` to see where `ergoemacs-mode` is slowing down.

**Comment by Foxly1990** [comment]
Thank you for response
