### ISSUE TITLE
ergoemacs movement keybindings broken with latest auctex

### ISSUE THREAD

**Issue by motherload** [ergoemacs/ergoemacs-mode#427]
Hello. After the last auctex update, the ergoemacs movement keybindings are useless. One must disable ergoemacs to properly edit latex files.

What happens is when I hit ALT+(direction) or even the arrow keys  over any characters that were typed using SHIFT, like any capital letters, _ + { : etc. the ergoemacs mode interprets as if I was typing SHIFT+ALT+(direction), and thus skips to the next bracket.

I'm using  ergoemacs-mode  20160912.1007 and  auctex 11.89.5.

**Comment by mattfidler** [comment]
How did you install auctex?  Did you use a manual installation.  When upgrading, you kept the same directory?  If so, perhaps clearing the ergoemacs-mode cache will fix your issues.  To do this:

- Start ergoemacs-mode
- Run the command `ergoemacs-mode-clear-cache`.  This can typically be accessed by <kbd>Alt</kbd>+<kbd>O</kbd> `ergoemacs-mode-clear-cache` <kbd>Enter</kbd>

Another possibility is you upgraded ergoemacs from an old version of ergoemacs.  There are others who reported this breaks functionality with many packages.  This is because these are build on old versions of ergoemacs-mode macros, which have been updated.  To fix this, you can:

- Delete ergoemacs-mode
- Restart Emacs
- Install ergoemacs-mode

Everything should work again.

Please let me know if these work for you.

**Comment by motherload** [comment]
Deleting ergoemacs-mode and reinstalling it fixed it for me.

I installed everything from melpa/elpa with package-install.

The problem actually was with characters that have different face sizes. Auctex does this automatically for subscript or superscript text, section headers, bold, etc. Moving the cursor over these characters would make it skip to the next (or previous, depending if you were navigating forward or backward) bracket, even if there were no bracket there, like in a subscript a_b.

Everything works again now. Thanks!!

**Comment by misakasim** [comment]
I encountered the same problem when I moved over a subscript or superscript. The reinstall does not work. What does work is to turn off the lowering and raising of the corresponding text via the Auctex menu or by adding the following line in the init file:
`(font-latex-script-display (quote (nil))`
Unfortunately, I lost the visual distinction of subscripts and superscripts.
